name: "Android CI: build and test"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allows you to run the workflow manually from the Actions tab

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Create signed apk and release bundle
        uses: ./.github/actions/build
        with:
          releaseBuild: 'true'
          buildApk: 'true'
          buildBundle: 'true'
      - name: Upload APK
        uses: actions/upload-artifact@v4.5.0
        with:
          name: unsigned-release-apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk
          if-no-files-found: error
      - name: Upload bundle
        uses: actions/upload-artifact@v4.5.0
        with:
          name: unsigned-release-bundle
          path: app/build/outputs/bundle/release/app-release.aab
          if-no-files-found: error